-- Ensure KHUYENMAI references LOAIKHUYENMAI and stores multi-product relations
ALTER TABLE IF EXISTS KHUYENMAI
  ADD COLUMN IF NOT EXISTS MALOAIKHUYENMAI INTEGER REFERENCES LOAIKHUYENMAI(MALOAIKHUYENMAI);

ALTER TABLE IF EXISTS KHUYENMAI
  ADD COLUMN IF NOT EXISTS SANPHAM_APDUNG_IDS TEXT;

ALTER TABLE IF EXISTS KHUYENMAI
  ADD COLUMN IF NOT EXISTS SANPHAM_TANG_IDS TEXT;

ALTER TABLE IF EXISTS KHUYENMAI
  ADD COLUMN IF NOT EXISTS SANPHAM_TANG_VARIANTS TEXT;
