-- Create per-order shipping address snapshot table
-- Run this once in your database (Supabase/Postgres)

CREATE TABLE IF NOT EXISTS public.diachigiaohang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  madonhang BIGINT NOT NULL REFERENCES public.donhang(madonhang) ON DELETE CASCADE,
  madiachi BIGINT,
  ten TEXT,
  sodienthoai TEXT,
  tinh TEXT,
  phuong TEXT,
  diachicuthe TEXT,
  diachi TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_diachigiaohang_madonhang ON public.diachigiaohang(madonhang);
